version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
    - "/infra/serviceA"
    groups:
      terraform-serviceA:
        patterns:
          - "*"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directories:
    - "/infra/serviceB"
    groups:
      terraform-serviceB:
        patterns:
          - "*"
    schedule:
      interval: "daily"
