version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
    - "/infra/serviceA"
    groups:
      ver-terraform-serviceA:
        applies-to: version-updates
        patterns:
          - "*"
      sec-terraform-serviceA:
        applies-to: security-updates
        patterns:
          - "*"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directories:
    - "/infra/serviceB"
    groups:
      ver-terraform-serviceB:
        applies-to: version-updates
        patterns:
          - "*"
      sec-terraform-serviceB:
        applies-to: security-updates
        patterns:
          - "*"
    schedule:
      interval: "daily"
